In this challenge, you will create a book recommendation algorithm using K-Nearest Neighbors.

In this project, you will use the Book-Crossings dataset, which contains 1.1 million ratings (scale of 1-10) of 270,000 books by 90,000 users. The dataset is already imported in the notebook, so no additional download is required.

Use NearestNeighbors from sklearn.neighbors to develop a model that shows books that are similar to a given book. The Nearest Neighbors algorithm measures the distance to determine the “closeness” of instances.

Create a function named get_recommends that takes a book title (from the dataset) as an argument and returns a list of 5 similar books with their distances from the book argument.

Notice that the data returned from get_recommends() is a list. The first element in the list is the book title passed into the function. The second element in the list is a list of five more lists. Each of the five lists contains a recommended book and the distance from the recommended book to the book passed into the function.

If you graph the dataset (optional), you will notice that most books are not rated frequently. To ensure statistical significance, remove from the dataset users with less than 200 ratings and books with less than 100 ratings.

The first three cells import libraries you may need and the data to use. The final cell is for testing. Write all your code in between those cells.

In [1]:
# import libraries (you may add additional imports but you may not have to)
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt

In [ ]:
# get data files
!wget https://cdn.freecodecamp.org/project-data/books/book-crossings.zip

!unzip book-crossings.zip

books_filename = 'BX-Books.csv'
ratings_filename = 'BX-Book-Ratings.csv'

In [3]:
# import csv data into dataframes
df_books = pd.read_csv(
    books_filename,
    encoding="ISO-8859-1",
    sep=";",
    header=0,
    names=["isbn", "title", "author"],
    usecols=["isbn", "title", "author"],
    dtype={"isbn": "str", "title": "str", "author": "str"},
)

df_ratings = pd.read_csv(
    ratings_filename,
    encoding="ISO-8859-1",
    sep=";",
    header=0,
    names=["user", "isbn", "rating"],
    usecols=["user", "isbn", "rating"],
    dtype={"user": "int32", "isbn": "str", "rating": "float32"},
)

In [4]:
df_books.head()

isbn                                              title  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

                 author  
0    Mark P. O. Morford  
1  Richard Bruce Wright  
2          Carlo D'Este  
3      Gina Bari Kolata  
4       E. J. W. Barber

In [5]:
df_ratings.head()

user        isbn  rating
0  276725  034545104X     0.0
1  276726  0155061224     5.0
2  276727  0446520802     0.0
3  276729  052165615X     3.0
4  276729  0521795028     6.0

In [6]:
df_ratings.shape

(1149780, 3)

In [7]:
user_rating_counts = df_ratings["user"].value_counts()
active_users = user_rating_counts[user_rating_counts >= 200].index

book_rating_counts = df_ratings["isbn"].value_counts()
popular_books = book_rating_counts[book_rating_counts >= 100].index

df_ratings = df_ratings[
    df_ratings["user"].isin(active_users) & df_ratings["isbn"].isin(popular_books)
]

In [8]:
df_ratings

user        isbn  rating
1456     277427  002542730X    10.0
1469     277427  0060930535     0.0
1471     277427  0060934417     0.0
1474     277427  0061009059     9.0
1484     277427  0140067477     0.0
...         ...         ...     ...
1147304  275970  0804111359     0.0
1147436  275970  140003065X     0.0
1147439  275970  1400031346     0.0
1147440  275970  1400031354     0.0
1147441  275970  1400031362     0.0

[49781 rows x 3 columns]

In [9]:
df_table = df_ratings.pivot_table(index="isbn", columns="user", values="rating").fillna(0)
df_table

user        254     2276    2766    2977    3363    4017    4385    6242    \
isbn                                                                         
002542730X     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
0060008032     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
0060096195     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
006016848X     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
0060173289     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...            ...     ...     ...     ...     ...     ...     ...     ...   
1573227331     0.0     0.0     0.0     0.0     0.0     0.0     0.0     6.0   
1573229326     0.0     0.0     0.0     0.0     0.0     0.0     0.0     6.0   
1573229571     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1592400876     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1878424319     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

user        6251    6323    ...  274004  274061  274301  274308  274808  \
isbn                        ...                                           
002542730X     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
0060008032     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
0060096195     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
006016848X     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
0060173289     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
...            ...     ...  ...     ...     ...     ...     ...     ...   
1573227331     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
1573229326     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
1573229571     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
1592400876     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
1878424319     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   

user        275970  277427  277478  277639  278418  
isbn                                                
002542730X     0.0    10.0     0.0     0.0     0.0  
0060008032     0.0     0.0     0.0     0.0     0.0  
0060096195     0.0     0.0     0.0     0.0     0.0  
006016848X     0.0     0.0     0.0     0.0     0.0  
0060173289     0.0     0.0     0.0     0.0     0.0  
...            ...     ...     ...     ...     ...  
1573227331     0.0     0.0     0.0     0.0     0.0  
1573229326     0.0     0.0     0.0     0.0     0.0  
1573229571     0.0     0.0     0.0     0.0     0.0  
1592400876     0.0     0.0     0.0     0.0     0.0  
1878424319     0.0     0.0     0.0     0.0     0.0  

[731 rows x 888 columns]

In [10]:
df_table.index = df_table.join(df_books.set_index("isbn"))["title"]
df_table.head(1)

user                                                254     2276    2766    \
title                                                                        
Politically Correct Bedtime Stories: Modern Tal...     0.0     0.0     0.0   

user                                                2977    3363    4017    \
title                                                                        
Politically Correct Bedtime Stories: Modern Tal...     0.0     0.0     0.0   

user                                                4385    6242    6251    \
title                                                                        
Politically Correct Bedtime Stories: Modern Tal...     0.0     0.0     0.0   

user                                                6323    ...  274004  \
title                                                       ...           
Politically Correct Bedtime Stories: Modern Tal...     0.0  ...     0.0   

user                                                274061  274301  274308  \
title                                                                        
Politically Correct Bedtime Stories: Modern Tal...     0.0     0.0     0.0   

user                                                274808  275970  277427  \
title                                                                        
Politically Correct Bedtime Stories: Modern Tal...     0.0     0.0    10.0   

user                                                277478  277639  278418  
title                                                                       
Politically Correct Bedtime Stories: Modern Tal...     0.0     0.0     0.0  

[1 rows x 888 columns]

In [11]:
print(df_table.values)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [12]:
def get_recommends(book=""):
    recommended_books = []
    knn = NearestNeighbors(n_neighbors=6, metric="cosine")
    knn.fit(df_table.values)

    distances, indices = knn.kneighbors([df_table.loc[book].values], n_neighbors=6)
    print(distances, indices)

    for i in range(5, 0, -1):
        recommended_books.append([df_table.index[indices[0][i]], distances[0][i]])

    return [book, recommended_books]

In [13]:
books = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")

[[0.         0.7234864  0.7677075  0.7699411  0.77085835 0.8016211 ]] [[435 108  27 182 120 625]]


In [14]:
books

["Where the Heart Is (Oprah's Book Club (Paperback))",
 [["I'll Be Seeing You", np.float32(0.8016211)],
  ['The Weight of Water', np.float32(0.77085835)],
  ['The Surgeon', np.float32(0.7699411)],
  ['I Know This Much Is True', np.float32(0.7677075)],
  ['The Lovely Bones: A Novel', np.float32(0.7234864)]]]

In [15]:
def test_book_recommendation():
    test_pass = True
    recommends = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
    if recommends[0] != "Where the Heart Is (Oprah's Book Club (Paperback))":
        test_pass = False
    recommended_books = [
        "I'll Be Seeing You",
        "The Weight of Water",
        "The Surgeon",
        "I Know This Much Is True",
    ]
    recommended_books_dist = [0.8, 0.77, 0.77, 0.77]
    for i in range(2):
        if recommends[1][i][0] not in recommended_books:
            test_pass = False
        if abs(recommends[1][i][1] - recommended_books_dist[i]) >= 0.05:
            test_pass = False
    if test_pass:
        print("You passed the challenge! 🎉🎉🎉🎉🎉")
    else:
        print("You haven't passed yet. Keep trying!")


test_book_recommendation()

[[0.         0.7234864  0.7677075  0.7699411  0.77085835 0.8016211 ]] [[435 108  27 182 120 625]]
You passed the challenge! 🎉🎉🎉🎉🎉
